import{a as L,S,i as a}from"./assets/vendor-5401a4b0.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))d(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&d(n)}).observe(document,{childList:!0,subtree:!0});function p(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function d(o){if(o.ep)return;o.ep=!0;const r=p(o);fetch(o.href,r)}})();async function m(t,e){const p="42356211-e192fc2ea90e5ac732e43fabf",r="https://pixabay.com/api/",n={key:p,q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15,page:e};return(await L.get(r,{params:n})).data}function v(t){return t.hits.map(e=>`
    <li class="gallery-item">
      <a href="${e.largeImageURL}">
        <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}">
      </a>
      <p><b>Likes: </b>${e.likes}</p>
      <p><b>Views: </b>${e.views}</p>
      <p><b>Comments: </b>${e.comments}</p>
      <p><b>Downloads: </b>${e.downloads}</p>
    </li>
  `).join("")}const w=document.querySelector(".form"),l=document.querySelector(".gallery"),f=document.querySelector("input"),i=document.querySelector(".load-more");let c="",s=1,P=15,u;const q=new S(".gallery a",{captions:!0,captionType:"attr",captionsData:"alt",captionPosition:"bottom",captionSelector:"img",captionDelay:250});function y(){const t=document.createElement("span");t.classList.add("loader"),i.parentNode.insertBefore(t,i.nextSibling)}function g(){const t=document.querySelector(".loader");t&&t.remove()}function E(){i.style.display="block"}function $(){i.style.display="none"}w.addEventListener("submit",async t=>{if(t.preventDefault(),c=f.value.trim(),!c){a.error({message:"Your request is missing. Please fill out the form",position:"topCenter"}),l.innerHTML="";return}s=1,l.innerHTML="",y();try{const e=await m(c,s);u=Math.ceil(e.totalHits/P),e.totalHits===0?a.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topCenter"}):(h(e),b(),s>=u&&a.info({message:"We're sorry, but you've reached the end of search results.",position:"topCenter"}))}catch(e){a.error({message:`An error occurred: ${e.message}`,position:"topCenter"})}finally{g()}f.value=""});i.addEventListener("click",async()=>{y(),s+=1;const t=await m(c,s);h(t),g(),b(),s>=u&&a.info({message:"We're sorry, but you've reached the end of search results.",position:"topCenter"});const e=l.firstElementChild.getBoundingClientRect().height;scrollBy({top:e*2,behavior:"smooth"})});function h(t){const e=v(t);l.insertAdjacentHTML("beforeend",e),q.refresh()}function b(){s>=u?$():E()}
//# sourceMappingURL=commonHelpers.js.map
